/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SvgRouteImport } from './routes/svg'
import { Route as TestRouteImport } from './routes/test'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as ChatChatidRouteImport } from './routes/chat/$chatid'
import { Route as ChatNewRouteImport } from './routes/chat/new'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SvgRoute = SvgRouteImport.update({
  id: '/svg',
  path: '/svg',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatidRoute = ChatChatidRouteImport.update({
  id: '/chat/$chatid',
  path: '/chat/$chatid',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/svg': typeof SvgRoute
  '/test': typeof TestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat/$chatid': typeof ChatChatidRoute
  '/chat/new': typeof ChatNewRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/svg': typeof SvgRoute
  '/test': typeof TestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat/$chatid': typeof ChatChatidRoute
  '/chat/new': typeof ChatNewRoute
  '/explore': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/svg': typeof SvgRoute
  '/test': typeof TestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat/$chatid': typeof ChatChatidRoute
  '/chat/new': typeof ChatNewRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/svg'
    | '/test'
    | '/auth/login'
    | '/auth/signup'
    | '/chat/$chatid'
    | '/chat/new'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/svg'
    | '/test'
    | '/auth/login'
    | '/auth/signup'
    | '/chat/$chatid'
    | '/chat/new'
    | '/explore'
  id:
    | '__root__'
    | '/'
    | '/svg'
    | '/test'
    | '/auth/login'
    | '/auth/signup'
    | '/chat/$chatid'
    | '/chat/new'
    | '/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SvgRoute: typeof SvgRoute
  TestRoute: typeof TestRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ChatChatidRoute: typeof ChatChatidRoute
  ChatNewRoute: typeof ChatNewRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svg': {
      id: '/svg'
      path: '/svg'
      fullPath: '/svg'
      preLoaderRoute: typeof SvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatid': {
      id: '/chat/$chatid'
      path: '/chat/$chatid'
      fullPath: '/chat/$chatid'
      preLoaderRoute: typeof ChatChatidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/new': {
      id: '/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SvgRoute: SvgRoute,
  TestRoute: TestRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ChatChatidRoute: ChatChatidRoute,
  ChatNewRoute: ChatNewRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
