/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/character/m4a1-gun-fps.glb -o src/components/Rendering/models/CharacterWithGun.tsx 
Author: BarcodeGames (https://sketchfab.com/barcodegames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m4-fps-weapon-animations-pack-v1-662fc74dda2646cfb48fc610705768ef
Title: M4 - FPS Weapon Animations Pack (v.1)
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { useKtx2LoaderExtender } from '../../../lib/ktx2'

type ActionName = 'Draw' | 'Reload' | 'Fire' | 'Reload_Empty' | 'Holster'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Bullet5_56x45mm_Bullet5_56x45mm_D_0: THREE.Mesh
    Mag1_M4_D_0: THREE.Mesh
    Bolt_M4_D_0: THREE.Mesh
    BoltCatch_M4_D_0: THREE.Mesh
    Trigger_M4_D_0: THREE.Mesh
    Bullet5_56x45mm_Bullet5_56x45mm_D_0_1: THREE.Mesh
    Mag2_M4_D_0: THREE.Mesh
    Safety_M4_D_0: THREE.Mesh
    Main_M4_D_0: THREE.Mesh
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Bullet5_56x45mm_D: THREE.MeshStandardMaterial
    M4_D: THREE.MeshStandardMaterial
    Hand_D: THREE.MeshStandardMaterial
    Glove_D: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

/**
 * Placement of the rig in camera space, so the barrel sits down the view centre.
 *
 * The pack is authored around a static `FPS_Camera_j_01` bone at model-space
 * (0.0109, 1.5393, -0.1006) and the rifle points along the model's +Z, while a
 * three.js camera looks down -Z. Anchoring that bone on the camera and yawing
 * the rig 180° reproduces the artist's framing exactly:
 *   gun body  (-0.22, -0.09, -0.22) · foregrip hand (-0.36) · trigger hand (-0.03)
 *
 * z is pushed an extra 0.12 forward of the raw anchor: the trigger hand only
 * sits ~2.5cm ahead of the anchor, so without the nudge it falls inside the
 * camera's 0.1 near plane and gets clipped away.
 */
const VIEWMODEL_ANCHOR: [number, number, number] = [0.0109, -1.5393, -0.2206]
const VIEWMODEL_YAW = Math.PI

/** Restart `action` as a one-shot pose that holds its final frame. */
function playPoseOnce(action: THREE.AnimationAction) {
  action.reset()
  action.setLoop(THREE.LoopOnce, 1)
  action.clampWhenFinished = true
  action.play()
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group | null>(null)
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, animations } = useGLTF('/models/ignore/character/m4a1-gun-fps.glb', true, true, extendWithKtx2)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Equipping plays Draw once and holds it on the final frame. Nothing else
  // drives the rig, so the weapon sits in that pose until it is equipped again.
  // Gated on the clip existing: useAnimations builds its action map a tick
  // after mount.
  const drawAction = actions.Draw
  const hasDrawn = React.useRef(false)
  React.useEffect(() => {
    if (!drawAction || hasDrawn.current) return
    hasDrawn.current = true
    playPoseOnce(drawAction)
  }, [drawAction])

  return (
    <group ref={group} {...props} position={VIEWMODEL_ANCHOR} rotation-y={VIEWMODEL_YAW} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="90bb898c5cd8456e986c226c4e48dc5bfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Hand_D} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Glove_D} skeleton={nodes.Object_8.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

