/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/character/m4a1-gun-fps.glb -o src/components/Rendering/models/CharacterWithGun.tsx 
Author: BarcodeGames (https://sketchfab.com/barcodegames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m4-fps-weapon-animations-pack-v1-662fc74dda2646cfb48fc610705768ef
Title: M4 - FPS Weapon Animations Pack (v.1)
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { useKtx2LoaderExtender } from '../../../lib/ktx2'

type ActionName = 'Draw' | 'Reload' | 'Fire' | 'Reload_Empty' | 'Holster'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Bullet5_56x45mm_Bullet5_56x45mm_D_0: THREE.Mesh
    Mag1_M4_D_0: THREE.Mesh
    Bolt_M4_D_0: THREE.Mesh
    BoltCatch_M4_D_0: THREE.Mesh
    Trigger_M4_D_0: THREE.Mesh
    Bullet5_56x45mm_Bullet5_56x45mm_D_0_1: THREE.Mesh
    Mag2_M4_D_0: THREE.Mesh
    Safety_M4_D_0: THREE.Mesh
    Main_M4_D_0: THREE.Mesh
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Bullet5_56x45mm_D: THREE.MeshStandardMaterial
    M4_D: THREE.MeshStandardMaterial
    Hand_D: THREE.MeshStandardMaterial
    Glove_D: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group | null>(null)
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, animations } = useGLTF('/models/ignore/character/m4a1-gun-fps.glb', true, true, extendWithKtx2)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="90bb898c5cd8456e986c226c4e48dc5bfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Hand_D} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Glove_D} skeleton={nodes.Object_8.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/m4a1-gun-fps.glb')
