/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/creatures/skeleton_dragon.glb -o src/components/Rendering/models/SkeletonDragon.tsx -t
Author: LivindorCreation (https://sketchfab.com/LivindorCreation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skeleton-dragon-0ae92a30d2c242069acd61ed432f6c32
Title: Skeleton Dragon
*/

import * as THREE from 'three'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useKtx2LoaderExtender } from '../../../lib/ktx2'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { useMemo, useRef, type JSX } from 'react'
import { BallCollider, RigidBody } from '@react-three/rapier'

// attack_4 -> roar, attack_5 -> fly roar, soar -> soar, travelrun -> run, travelmove -> walk, travelidle -> idle , stunidle ->  idle / seems like eating
type ActionName = 'attack_4' | 'attack_5' | 'soar' |'travelrun' | 'travelmove' | 'travelidle' | 'stunidle';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Mob_deadland_skeleton_dragon: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

interface SkeletonDragonProps {
  type?: 'flying' | 'idle',
  collider?: boolean,
  scale?: number,
  props: JSX.IntrinsicElements['group']
}

export function SkeletonDragon({ type, collider, scale, ...props }: SkeletonDragonProps) {
  const group = useRef<THREE.Group | null>(null);
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, animations } = useGLTF('/models/ignore/creatures/skeleton_dragon.glb', true, true, extendWithKtx2)
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  useAnimations(animations, group)
  const SCALE_MULTIPLIER = 4;
  const SCALE = scale ? scale * SCALE_MULTIPLIER : SCALE_MULTIPLIER;
  const ABDOMEN_RADIUS = SCALE * 0.6;
  const ABDOMEN_HEIGHT = SCALE * 0.5;
  const body = (
    <group ref={group} scale={SCALE} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Skeleton_dragonfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="mob_deadland_skeleton_dragon" scale={2}>
                  <group name="root" rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                    <group name="Object_7">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Mob_deadland_skeleton_dragon} skeleton={nodes.Object_10.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
  if (!collider) return body
  return (
    <RigidBody type="fixed" colliders={false} {...props}>
      {body}
      <BallCollider args={[ABDOMEN_RADIUS]} position={[0, ABDOMEN_HEIGHT, 0]} />
    </RigidBody>
  )
}
