/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/map/mobile_home_with_collider.glb -o src/components/Rendering/map/AnimatedShrine.tsx 
*/

import * as THREE from 'three'
import { useEffect, useMemo, useRef, type JSX } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { CuboidCollider, RigidBody, type RapierRigidBody } from '@react-three/rapier'
import { useKtx2LoaderExtender } from '../../../lib/ktx2'
import type { SpawnZone } from '../../World/worldTypes'

type ActionName = 'Scene'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    VISIBLE_COL_MOVING_JOINT_1VISIBLE_COL_MOVING_JOINT_2: THREE.Mesh
    COL_MOVING_GEAR_1: THREE.Mesh
    VISIBLE_COL_MOVING_JOINT_1: THREE.Mesh
    COL_MOVING_FLOOR_1: THREE.Mesh
    COL_MOVING_FLOOR_2: THREE.Mesh
    COL_MOVING_FLOOR_3: THREE.Mesh
    COL_MOVING_FLOOR_6: THREE.Mesh
    COL_MOVING_WALL_1: THREE.Mesh
    COL_MOVING_WALL_2: THREE.Mesh
    COL_MOVING_WALL_3: THREE.Mesh
    COL_MOVING_WALL_4: THREE.Mesh
    COL_MOVING_WALL_5: THREE.Mesh
    COL_MOVING_WALL_6: THREE.Mesh
    COL_MOVING_FLOOR_4: THREE.Mesh
    COL_MOVING_FLOOR_5: THREE.Mesh
    building_D_pipes001_flame_0: THREE.Mesh
    building_D_pipes001_house_baked_0001: THREE.Mesh
    building_D_pipes001_house_baked_0002: THREE.Mesh
    building_D_pipes001_house_baked_0003: THREE.Mesh
    building_D_pipes001_pipes_moving_baked_0: THREE.Mesh
    building_pipes: THREE.Mesh
    BezierCurve003_foliage_baked_0: THREE.Mesh
    BezierCurve003_foliage_baked_0001: THREE.Mesh
    bridge_suspended002_platform_calm_0: THREE.Mesh
    bridge_suspended010_platform_unstable_baked_0: THREE.Mesh
    building_D_pipes_pipes_moving_baked_0: THREE.Mesh
    rock_left_rock_A_0: THREE.Mesh
    rock_left_rock_B_0: THREE.Mesh
    rock_left_ROCKS_SMALL_0: THREE.Mesh
    rock_left_stones_0: THREE.Mesh
    rock_middle_rock_middle_baked_0: THREE.Mesh
    stone_small_C001_rock_top_baked_0: THREE.Mesh
    stone_small_C002_rock_right_baked_0: THREE.Mesh
    COL_FLOOR_1: THREE.Mesh
    COL_FLOOR_2: THREE.Mesh
    COL_FLOOR_16: THREE.Mesh
    COL_FLOOR_3: THREE.Mesh
    COL_FLOOR_4: THREE.Mesh
    COL_FLOOR_5: THREE.Mesh
    COL_FLOOR_17: THREE.Mesh
    COL_FLOOR_18: THREE.Mesh
    COL_FLOOR_20: THREE.Mesh
    COL_FLOOR_21: THREE.Mesh
    COL_FLOOR_22: THREE.Mesh
    COL_FLOOR_23: THREE.Mesh
    COL_FLOOR_27: THREE.Mesh
    COL_FLOOR_28: THREE.Mesh
    COL_FLOOR_29: THREE.Mesh
    COL_FLOOR_30: THREE.Mesh
    COL_FLOOR_19: THREE.Mesh
    COL_FLOOR_31: THREE.Mesh
    COL_FLOOR_32: THREE.Mesh
    COL_FLOOR_33: THREE.Mesh
    COL_FLOOR_34: THREE.Mesh
    COL_FLOOR_35: THREE.Mesh
  }
  materials: {
    pipes_moving_baked: THREE.MeshBasicMaterial
    flame: THREE.MeshBasicMaterial
    house_baked: THREE.MeshBasicMaterial
    foliage_baked: THREE.MeshBasicMaterial
    platform_calm: THREE.MeshBasicMaterial
    platform_unstable_baked: THREE.MeshBasicMaterial
    rock_A: THREE.MeshBasicMaterial
    rock_middle_baked: THREE.MeshBasicMaterial
    rock_top_baked: THREE.MeshBasicMaterial
    rock_right_baked: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

const MODEL_URL = '/models/ignore/map/mobile_home_with_collider.glb'

/**
 * Spawn zone: the standable top of the COL_FLOOR_4 collider, read straight off
 * its proxy box in component space (World renders this map at mapScale = 1).
 * Format: [x, z, radius, floorY].
 */
export const MobileHomeSpawnZones: SpawnZone[] = [
  [-3.09, 41.52, 6.5, 9.37], // COL_FLOOR_4 deck
]

/**
 * Blender collider naming convention (see docs/WorldBuilding.md):
 *   COL_*          static collider, never rendered
 *   COL_MOVING_*   collider that rides the skeletal animation, never rendered
 *   VISIBLE_COL_*  collider that is also part of the visible mesh
 * Every other mesh is render-only.
 */
const isMovingCollider = (name: string) =>
  name.startsWith('COL_MOVING_') || name.startsWith('VISIBLE_COL_MOVING_')

const isCollider = (name: string) =>
  name.startsWith('COL_') || name.startsWith('VISIBLE_COL')

interface ColliderBox {
  name: string
  halfExtents: [number, number, number]
  center: [number, number, number]
  rotation: [number, number, number]
  localCenter: THREE.Vector3
}

export function MobileHome(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group | null>(null)
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, nodes, materials, animations } = useGLTF(MODEL_URL, true, true, extendWithKtx2) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Scene?.reset().fadeIn(0.5).play()
    return () => {
      actions.Scene?.fadeOut(0.5)
    }
  }, [actions])

  /**
   * Read every COL_* / VISIBLE_COL_* mesh off the loaded scene (bind pose — all
   * animation scale tracks are constant) and turn its bounding box into a cheap
   * cuboid. Static proxies go in one frozen body; COL_MOVING_* proxies get a
   * kinematic body each so they can follow the animation.
   */
  const { staticBoxes, movingBoxes } = useMemo(() => {
    const staticBoxes: ColliderBox[] = []
    const movingBoxes: ColliderBox[] = []
    scene.updateMatrixWorld(true)
    scene.traverse((object) => {
      const mesh = object as THREE.Mesh
      if (!mesh.isMesh || !isCollider(mesh.name)) return
      mesh.geometry.computeBoundingBox()
      const bounds = mesh.geometry.boundingBox
      if (!bounds) return
      const half = new THREE.Vector3().subVectors(bounds.max, bounds.min).multiplyScalar(0.5)
      const localCenter = bounds.getCenter(new THREE.Vector3())
      const position = new THREE.Vector3()
      const quaternion = new THREE.Quaternion()
      const scale = new THREE.Vector3()
      mesh.matrixWorld.decompose(position, quaternion, scale)
      const euler = new THREE.Euler().setFromQuaternion(quaternion)
      const center = localCenter.clone().applyMatrix4(mesh.matrixWorld)
      const box: ColliderBox = {
        name: mesh.name,
        halfExtents: [
          Math.abs(half.x * scale.x),
          Math.abs(half.y * scale.y),
          Math.abs(half.z * scale.z),
        ],
        center: [center.x, center.y, center.z],
        rotation: [euler.x, euler.y, euler.z],
        localCenter,
      }
      if (isMovingCollider(mesh.name)) movingBoxes.push(box)
      else staticBoxes.push(box)
    })
    return { staticBoxes, movingBoxes }
  }, [scene])

  // The rendered COL_MOVING_* meshes ride the skeleton, so we sample their world
  // matrices each frame to drive the kinematic bodies that represent them.
  const movingMeshes = useRef(new Map<string, THREE.Mesh>())
  useEffect(() => {
    const root = group.current
    if (!root) return
    const found = new Map<string, THREE.Mesh>()
    root.traverse((object) => {
      const mesh = object as THREE.Mesh
      if (mesh.isMesh && isMovingCollider(mesh.name)) found.set(mesh.name, mesh)
    })
    movingMeshes.current = found
  }, [scene])

  const movingBodies = useRef<(RapierRigidBody | null)[]>([])
  const scratch = useMemo(() => ({
    rootInverse: new THREE.Matrix4(),
    local: new THREE.Matrix4(),
    position: new THREE.Vector3(),
    quaternion: new THREE.Quaternion(),
    scale: new THREE.Vector3(),
    center: new THREE.Vector3(),
  }), [])

  useFrame(() => {
    const root = group.current
    if (!root || movingBoxes.length === 0) return
    scratch.rootInverse.copy(root.matrixWorld).invert()
    movingBoxes.forEach((box, index) => {
      const mesh = movingMeshes.current.get(box.name)
      const body = movingBodies.current[index]
      if (!mesh || !body) return
      // The mixer updates bone locals; refresh matrices so we sample this frame's pose.
      mesh.updateWorldMatrix(true, false)
      scratch.local.copy(scratch.rootInverse).multiply(mesh.matrixWorld)
      scratch.local.decompose(scratch.position, scratch.quaternion, scratch.scale)
      scratch.center.copy(box.localCenter).applyMatrix4(scratch.local)
      body.setNextKinematicTranslation({ x: scratch.center.x, y: scratch.center.y, z: scratch.center.z })
      body.setNextKinematicRotation({
        x: scratch.quaternion.x,
        y: scratch.quaternion.y,
        z: scratch.quaternion.z,
        w: scratch.quaternion.w,
      })
    })
  })

  return (
    <group ref={group} {...props} dispose={null}>
      {/* COL_* static colliders — invisible, never rendered */}
      <RigidBody type="fixed" colliders={false}>
        {staticBoxes.map((box) => (
          <CuboidCollider key={box.name} args={box.halfExtents} position={box.center} rotation={box.rotation} />
        ))}
      </RigidBody>

      {/* COL_MOVING_* animated colliders — invisible, follow the animation each frame */}
      {movingBoxes.map((box, index) => (
        <RigidBody
          key={box.name}
          ref={(body) => {
            movingBodies.current[index] = body
          }}
          type="kinematicPosition"
          colliders={false}
          position={box.center}
          rotation={box.rotation}
        >
          <CuboidCollider args={box.halfExtents} />
        </RigidBody>
      ))}

      <group name="Scene">
        <group name="Mobile-Home-Map" rotation={[Math.PI / 2, 0, Math.PI]}>
          <group name="VISIBLE_MESH" rotation={[-Math.PI, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature001" position={[-154.142, 606.122, -66.65]} rotation={[0, 0, -Math.PI / 2]} scale={100}>
                  <group name="Object_23">
                    <group name="_rootJoint">
                      <group name="arm_A_00">
                        <group name="arm_B_01">
                          <group name="building_D_pipes003" rotation={[-Math.PI / 2, 0.744, -Math.PI / 2]}>
                            <mesh name="VISIBLE_COL_MOVING_JOINT_1VISIBLE_COL_MOVING_JOINT_2" geometry={nodes.VISIBLE_COL_MOVING_JOINT_1VISIBLE_COL_MOVING_JOINT_2.geometry} material={materials.pipes_moving_baked} />
                          </group>
                        </group>
                        <group name="building_D_pipes002" rotation={[-Math.PI / 2, -0.856, -Math.PI / 2]}>
                          <mesh visible={false} name="COL_MOVING_GEAR_1" geometry={nodes.COL_MOVING_GEAR_1.geometry} material={nodes.COL_MOVING_GEAR_1.material} position={[-3.22, 8.373, 7.216]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[3.37, 3.95, 3.43]} />
                          <mesh name="VISIBLE_COL_MOVING_JOINT_1" geometry={nodes.VISIBLE_COL_MOVING_JOINT_1.geometry} material={materials.pipes_moving_baked} />
                        </group>
                      </group>
                      <group name="home_02">
                        <group name="building_D_pipes001" rotation={[0, -1.571, 0]} scale={1.052}>
                          <mesh visible={false} name="COL_MOVING_FLOOR_1" geometry={nodes.COL_MOVING_FLOOR_1.geometry} material={nodes.COL_MOVING_FLOOR_1.material} position={[-4.71, -2.985, 0.891]} rotation={[Math.PI / 2, 0.017, 0]} scale={[6.577, 0.2, 3.669]} />
                          <mesh visible={false} name="COL_MOVING_FLOOR_2" geometry={nodes.COL_MOVING_FLOOR_2.geometry} material={nodes.COL_MOVING_FLOOR_2.material} position={[-3.521, 4.087, -0.129]} rotation={[Math.PI / 2, -0.052, 0]} scale={[3.06, 0.219, 4.248]} />
                          <mesh visible={false} name="COL_MOVING_FLOOR_3" geometry={nodes.COL_MOVING_FLOOR_3.geometry} material={nodes.COL_MOVING_FLOOR_3.material} position={[-3.53, -6.276, -0.229]} rotation={[2.217, 0, 0]} scale={[3.06, 0.219, 2.081]} />
                          <mesh visible={false} name="COL_MOVING_FLOOR_6" geometry={nodes.COL_MOVING_FLOOR_6.geometry} material={nodes.COL_MOVING_FLOOR_6.material} position={[-3.008, -10.049, -1.675]} rotation={[Math.PI / 2, -0.052, 0.035]} scale={[3.193, 0.181, 5.427]} />
                          <mesh visible={false} name="COL_MOVING_WALL_1" geometry={nodes.COL_MOVING_WALL_1.geometry} material={nodes.COL_MOVING_WALL_1.material} position={[-0.613, -3.21, 3.205]} rotation={[Math.PI / 2, 0.017, 0]} scale={[0.257, 2.376, 3.26]} />
                          <mesh visible={false} name="COL_MOVING_WALL_2" geometry={nodes.COL_MOVING_WALL_2.geometry} material={nodes.COL_MOVING_WALL_2.material} position={[-11.409, -2.582, 2.921]} rotation={[Math.PI / 2, 0.017, 0]} scale={[0.257, 2.376, 3.26]} />
                          <mesh visible={false} name="COL_MOVING_WALL_3" geometry={nodes.COL_MOVING_WALL_3.geometry} material={nodes.COL_MOVING_WALL_3.material} position={[-0.637, 4.277, 2.613]} rotation={[Math.PI / 2, 0.017, 0]} scale={[0.257, 2.376, 3.26]} />
                          <mesh visible={false} name="COL_MOVING_WALL_4" geometry={nodes.COL_MOVING_WALL_4.geometry} material={nodes.COL_MOVING_WALL_4.material} position={[-6.296, 4.516, 2.483]} rotation={[Math.PI / 2, 0.017, 0]} scale={[0.257, 2.376, 3.26]} />
                          <mesh visible={false} name="COL_MOVING_WALL_5" geometry={nodes.COL_MOVING_WALL_5.geometry} material={nodes.COL_MOVING_WALL_5.material} position={[0.124, -9.853, 1.188]} rotation={[Math.PI / 2, 0.017, 0]} scale={[0.257, 2.376, 3.26]} />
                          <mesh visible={false} name="COL_MOVING_WALL_6" geometry={nodes.COL_MOVING_WALL_6.geometry} material={nodes.COL_MOVING_WALL_6.material} position={[-6.762, -9.74, 1.24]} rotation={[Math.PI / 2, 0.017, 0]} scale={[0.257, 2.376, 3.26]} />
                          <mesh visible={false} name="COL_MOVING_FLOOR_4" geometry={nodes.COL_MOVING_FLOOR_4.geometry} material={nodes.COL_MOVING_FLOOR_4.material} position={[0.184, 0.262, -0.047]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.882, 1.825, 2.034]} />
                          <mesh visible={false} name="COL_MOVING_FLOOR_5" geometry={nodes.COL_MOVING_FLOOR_5.geometry} material={nodes.COL_MOVING_FLOOR_5.material} position={[-5.862, 0.151, 0.283]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.882, 1.825, 2.034]} />
                          <mesh name="building_D_pipes001_flame_0" geometry={nodes.building_D_pipes001_flame_0.geometry} material={materials.flame} />
                          <mesh name="building_D_pipes001_house_baked_0001" geometry={nodes.building_D_pipes001_house_baked_0001.geometry} material={materials.house_baked} />
                          <mesh name="building_D_pipes001_house_baked_0002" geometry={nodes.building_D_pipes001_house_baked_0002.geometry} material={materials.house_baked} />
                          <mesh name="building_D_pipes001_house_baked_0003" geometry={nodes.building_D_pipes001_house_baked_0003.geometry} material={materials.house_baked} />
                          <mesh name="building_D_pipes001_pipes_moving_baked_0" geometry={nodes.building_D_pipes001_pipes_moving_baked_0.geometry} material={materials.pipes_moving_baked} />
                          <mesh name="building_pipes" geometry={nodes.building_pipes.geometry} material={materials.house_baked} />
                        </group>
                      </group>
                      <group name="root_03" />
                    </group>
                  </group>
                </group>
                <group name="BezierCurve003" position={[1208.747, -1918.884, -205.693]} rotation={[0, 0, -Math.PI / 2]} scale={[73.461, 114.205, 73.461]}>
                  <mesh name="BezierCurve003_foliage_baked_0" geometry={nodes.BezierCurve003_foliage_baked_0.geometry} material={materials.foliage_baked} />
                  <mesh name="BezierCurve003_foliage_baked_0001" geometry={nodes.BezierCurve003_foliage_baked_0001.geometry} material={materials.foliage_baked} />
                </group>
                <group name="bridge_suspended002" position={[-2351.661, 3178, 1078.609]} rotation={[0, 0, -2.834]} scale={100}>
                  <mesh name="bridge_suspended002_platform_calm_0" geometry={nodes.bridge_suspended002_platform_calm_0.geometry} material={materials.platform_calm} />
                </group>
                <group name="bridge_suspended010" position={[641.867, -5206.883, 755.615]} rotation={[0, 0, -Math.PI / 2]} scale={100}>
                  <mesh name="bridge_suspended010_platform_unstable_baked_0" geometry={nodes.bridge_suspended010_platform_unstable_baked_0.geometry} material={materials.platform_unstable_baked} />
                </group>
                <group name="building_D_pipes" position={[70.961, 517.462, 1209.234]} rotation={[0, 0, Math.PI]} scale={100}>
                  <mesh name="building_D_pipes_pipes_moving_baked_0" geometry={nodes.building_D_pipes_pipes_moving_baked_0.geometry} material={materials.pipes_moving_baked} />
                </group>
                <group name="rock_left" position={[-1129.299, 4955.811, 5110.5]} rotation={[0, 0, -Math.PI / 2]} scale={100}>
                  <mesh name="rock_left_rock_A_0" geometry={nodes.rock_left_rock_A_0.geometry} material={materials.rock_A} />
                  <mesh name="rock_left_rock_B_0" geometry={nodes.rock_left_rock_B_0.geometry} material={materials.rock_A} />
                  <mesh name="rock_left_ROCKS_SMALL_0" geometry={nodes.rock_left_ROCKS_SMALL_0.geometry} material={materials.rock_A} />
                  <mesh name="rock_left_stones_0" geometry={nodes.rock_left_stones_0.geometry} material={materials.rock_A} />
                </group>
                <group name="rock_middle" position={[-1129.299, 4955.811, 5110.5]} rotation={[0, 0, -Math.PI / 2]} scale={100}>
                  <mesh name="rock_middle_rock_middle_baked_0" geometry={nodes.rock_middle_rock_middle_baked_0.geometry} material={materials.rock_middle_baked} />
                </group>
                <group name="stone_small_C001" position={[-1129.299, 4955.811, 5110.5]} rotation={[0, 0, -Math.PI / 2]} scale={100}>
                  <mesh name="stone_small_C001_rock_top_baked_0" geometry={nodes.stone_small_C001_rock_top_baked_0.geometry} material={materials.rock_top_baked} />
                </group>
                <group name="stone_small_C002" position={[-1129.299, 4955.811, 5110.5]} rotation={[0, 0, -Math.PI / 2]} scale={100}>
                  <mesh name="stone_small_C002_rock_right_baked_0" geometry={nodes.stone_small_C002_rock_right_baked_0.geometry} material={materials.rock_right_baked} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
