/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/map/the_last_stronghold_animated_floating_collider.glb -o src/components/Rendering/map/StrongholdCollider.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    COL_CONE_1: THREE.Mesh
    COL_CONE_2: THREE.Mesh
    COL_CONE_3: THREE.Mesh
    COL_CONE_4: THREE.Mesh
    Cube001: THREE.Mesh
    Sphere: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/the_last_stronghold_animated_floating_collider.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002}>
        <mesh geometry={nodes.COL_CONE_1.geometry} material={nodes.COL_CONE_1.material} position={[381.028, 2916.008, -3695.573]} rotation={[Math.PI / 2, -Math.PI / 9, 0.279]} scale={[1293.089, 905.708, 1183.968]} />
        <mesh geometry={nodes.COL_CONE_2.geometry} material={nodes.COL_CONE_2.material} position={[2264.451, -239.563, -3649.608]} rotation={[Math.PI / 2, -Math.PI / 9, 0.279]} scale={[1293.089, 905.708, 1183.968]} />
        <mesh geometry={nodes.COL_CONE_3.geometry} material={nodes.COL_CONE_3.material} position={[2804.098, -2869.565, -6018.814]} rotation={[Math.PI / 2, -Math.PI / 9, 0.192]} scale={[736.57, 905.708, 872.972]} />
        <mesh geometry={nodes.COL_CONE_4.geometry} material={nodes.COL_CONE_4.material} position={[283.008, -2743.522, -2289.68]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[807.499, 676.553, 703.833]} />
      </group>
      <instancedMesh args={[nodes.Cube001.geometry, nodes.Cube001.material, 11]} instanceMatrix={nodes.Cube001.instanceMatrix} />
      <instancedMesh args={[nodes.Sphere.geometry, nodes.Sphere.material, 8]} instanceMatrix={nodes.Sphere.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/the_last_stronghold_animated_floating_collider.glb')
